(()=>{
const dialog=document.querySelector('#labGame'),task=document.querySelector('#labTask'),msg=document.querySelector('#labMessage');
const stages=[
 {title:'Энергетический реактор',equation:'x + 7 = 18',type:'choice',options:[9,10,11,12],answer:11,hint:'Какое число вместе с 7 даёт 18?'},
 {title:'Система баланса',equation:'2x + 5 = 17',type:'steps',steps:[{label:'Убери лишнее с обеих сторон',options:['− 5','+ 5','÷ 2'],answer:'− 5',result:'2x = 12'},{label:'Освободи x',options:['× 2','÷ 2','− 2'],answer:'÷ 2',result:'x = 6'}],answer:6,hint:'Сначала убери +5 противоположным действием.'},
 {title:'Формульный модуль',equation:'3x + 4 = 19',type:'drag',tokens:['− 4','+ 4','÷ 3','× 3'],answers:['− 4','÷ 3'],answer:5,hint:'Сначала убери 4, затем коэффициент 3.'},
 {title:'Дозатор раствора',equation:'4x − 8 = 24',type:'dial',options:[4,6,7,8,9],answer:8,hint:'Прибавь 8 к обеим частям, затем раздели на 4.'},
 {title:'Главный реактор',equation:'3(x + 2) = 27',type:'code',steps:[{label:'Первое действие',options:['÷ 3','− 2','+ 3'],answer:'÷ 3',result:'x + 2 = 9'},{label:'Второе действие',options:['+ 2','− 2','÷ 2'],answer:'− 2',result:'x = 7'}],answer:7,hint:'Сначала убери множитель 3 перед скобками.'}
];
let state,ctx,gain;
function audio(){if(ctx){ctx.resume();return}ctx=new(window.AudioContext||window.webkitAudioContext)();gain=ctx.createGain();gain.gain.value=.18;gain.connect(ctx.destination)}
function sound(kind){if(!ctx)return;const notes={click:[520],correct:[392,523,659],wrong:[170,145],liquid:[260,310,370],machine:[120,180,240,360],reward:[392,494,587,784]}[kind]||[440];notes.forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+i*.09;o.type=kind==='machine'?'square':'triangle';o.frequency.value=f;g.gain.setValueAtTime(.09,t);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.connect(g).connect(gain);o.start(t);o.stop(t+.2)})}
function reset(){state={stage:0,xp:0,mistakes:0,hints:0,step:0,start:Date.now(),dial:4,drag:[]};document.querySelectorAll('#labModules i').forEach(x=>x.classList.remove('on'));document.querySelector('.reactor').classList.remove('online');update()}
window.openLabGame=()=>{audio();sound('click');reset();intro();if(!dialog.open)dialog.showModal()};
function intro(){task.innerHTML=`<div class="lab-intro"><small>ЭКСПЕРИМЕНТ 01</small><h2>Аварийный запуск</h2><p>Найди неизвестные и восстанови пять модулей лесной установки.</p><div><span>5 экспериментов</span><span>≈ 5–7 минут</span><span>★ до 3 звёзд</span></div><button id="labStart">ЗАПУСТИТЬ ЛАБОРАТОРИЮ</button></div>`;document.querySelector('#labStart').onclick=()=>{sound('click');render()}}
function render(){const s=stages[state.stage];state.step=0;state.drag=[];msg.textContent='';document.querySelector('#otterSpeech').textContent=['Система ждёт код. Начнём с простого.','Проверим баланс с обеих сторон.','Собери правильную последовательность операций.','Настрой дозатор точным поворотом.','Последний модуль. Реактор почти нас понял!'][state.stage];let ui='';if(s.type==='choice')ui=answers(s.options);if(s.type==='steps'||s.type==='code')ui=stepUI(s);if(s.type==='drag')ui=`<div class="formula-drop" id="formulaDrop">Перетащи сюда 2 действия по порядку</div><div class="formula-tokens">${s.tokens.map(x=>`<button data-token="${x}">${x}</button>`).join('')}</div><button class="lab-confirm" id="formulaCheck">ПОДАТЬ ФОРМУЛУ</button>`;if(s.type==='dial')ui=`<div class="lab-dial"><button id="dialPrev">‹</button><div><small>ЗНАЧЕНИЕ x</small><b id="labDialValue">4</b></div><button id="dialNext">›</button></div><button class="lab-confirm" id="dialCheck">ПОДАТЬ РАСТВОР</button>`;task.innerHTML=`<div class="lab-task-head"><small>МОДУЛЬ ${state.stage+1} / 5</small><h2>${s.title}</h2></div><div class="lab-equation" id="labEquation">${s.equation}</div><div class="lab-mechanic">${ui}</div>`;bind(s)}
function answers(a){return`<div class="lab-answers">${a.map(x=>`<button data-answer="${x}">x = ${x}</button>`).join('')}</div>`}
function stepUI(s){const p=s.steps[state.step];return`<div class="step-caption">${p.label}</div><div class="lab-answers operations">${p.options.map(x=>`<button data-operation="${x}">${x}</button>`).join('')}</div>`}
function bind(s){task.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>check(+b.dataset.answer,b));task.querySelectorAll('[data-operation]').forEach(b=>b.onclick=()=>operation(s,b.dataset.operation,b));if(s.type==='drag')bindFormula(s);if(s.type==='dial'){document.querySelector('#dialPrev').onclick=()=>turn(s,-1);document.querySelector('#dialNext').onclick=()=>turn(s,1);document.querySelector('#dialCheck').onclick=e=>check(state.dial,e.currentTarget)}}
function operation(s,value,b){sound('click');const p=s.steps[state.step];if(value!==p.answer)return wrong(b);b.classList.add('correct');document.querySelector('#labEquation').textContent=p.result;state.step++;if(state.step===s.steps.length)setTimeout(()=>check(s.answer,b),650);else setTimeout(()=>{document.querySelector('.lab-mechanic').innerHTML=stepUI(s);bind(s)},500)}
function bindFormula(s){document.querySelectorAll('[data-token]').forEach(b=>{b.onclick=()=>{if(state.drag.length<2){sound('click');state.drag.push(b.dataset.token);b.disabled=true;document.querySelector('#formulaDrop').textContent=state.drag.join('  →  ')}};let sx,sy;b.onpointerdown=e=>{sx=e.clientX;sy=e.clientY;b.setPointerCapture(e.pointerId);b.classList.add('dragging')};b.onpointermove=e=>{if(b.classList.contains('dragging'))b.style.transform=`translate(${e.clientX-sx}px,${e.clientY-sy}px)`};b.onpointerup=e=>{b.classList.remove('dragging');b.style.transform='';const r=document.querySelector('#formulaDrop').getBoundingClientRect();if(e.clientX>r.left&&e.clientX<r.right&&e.clientY>r.top&&e.clientY<r.bottom)b.click()}});document.querySelector('#formulaCheck').onclick=e=>state.drag.join('|')===s.answers.join('|')?check(s.answer,e.currentTarget):wrong(e.currentTarget)}
function turn(s,d){sound('click');let i=s.options.indexOf(state.dial);i=(i+d+s.options.length)%s.options.length;state.dial=s.options[i];document.querySelector('#labDialValue').textContent=state.dial;document.querySelector('.lab-dial>div').animate([{transform:'rotateX(0)'},{transform:`rotateX(${d*70}deg)`},{transform:'rotateX(0)'}],{duration:280})}
function check(v,b){const s=stages[state.stage];if(v!==s.answer)return wrong(b);sound(state.stage===4?'machine':'correct');state.xp+=state.stage===4?30:15;b.classList.add('correct');document.querySelector('#otterSpeech').textContent=['Отлично! Энергия пошла.','Баланс восстановлен!','Формула принята.','Дозировка идеальна.','Вот это расчёт! Реактор запускается!'][state.stage];activate();setTimeout(()=>{state.stage++;state.stage===5?finish():render()},1100)}
function wrong(b){sound('wrong');state.mistakes++;b.classList.add('wrong');msg.textContent='Формула почти стабильна. Проверь действие.';setTimeout(()=>b.classList.remove('wrong'),450)}
function activate(){document.querySelectorAll('#labModules i')[state.stage].classList.add('on');document.querySelector('.lab-scene').classList.add('pulse');setTimeout(()=>document.querySelector('.lab-scene').classList.remove('pulse'),800);update()}
function update(){const done=document.querySelectorAll('#labModules i.on').length;document.querySelector('#labXP').textContent=state?.xp||0;document.querySelector('#labProgress').textContent=done+' / 5';document.querySelector('#labDots').textContent=Array.from({length:5},(_,i)=>i<done?'●':'○').join(' ')}
function stars(){return state.mistakes<=1&&state.hints<=1?3:state.mistakes<=4?2:1}
function finish(){sound('reward');document.querySelector('.reactor').classList.add('online');const s=stars(),xp=state.xp+50,time=Math.round((Date.now()-state.start)/1000);document.querySelector('#labStars').textContent='★'.repeat(s)+'☆'.repeat(3-s);task.innerHTML=`<div class="lab-result"><span>◆</span><h2>Лаборатория запущена!</h2><p>Все модули работают. Энергетический кристалл стабилен.</p><h3>★ ${s} &nbsp; +${xp} XP &nbsp; ● 40</h3><small>Время ${Math.floor(time/60)}:${String(time%60).padStart(2,'0')} · Ошибки ${state.mistakes}</small><div><button id="labAgain">НАЧАТЬ ЗАНОВО</button><button id="labHome">НА ПОЛЯНУ</button></div></div>`;localStorage.setItem('equationLabProgress',JSON.stringify({bestStars:s,bestTime:time,totalXP:xp,coins:40,completed:true,unlockedExperiment:2}));window.dispatchEvent(new CustomEvent('lab-complete',{detail:{xp,coins:40,stars:s}}));document.querySelector('#labAgain').onclick=()=>window.openLabGame();document.querySelector('#labHome').onclick=()=>dialog.close()}
document.querySelector('#labHint').onclick=()=>{state.hints++;msg.textContent=stages[state.stage].hint;sound('click')};document.querySelector('#labExit').onclick=()=>dialog.close();document.querySelector('#labSound').onclick=e=>{gain.gain.value=gain.gain.value?0:.18;e.currentTarget.textContent=gain.gain.value?'🔊':'🔇'};document.addEventListener('keydown',e=>{if(dialog.open&&stages[state.stage]?.type==='dial'){if(e.key==='ArrowLeft')document.querySelector('#dialPrev').click();if(e.key==='ArrowRight')document.querySelector('#dialNext').click()}})
})();
