(()=>{
const dialog=document.querySelector('#tournamentGame'),task=document.querySelector('#tournamentTask'),msg=document.querySelector('#tournamentMessage');
const rounds=[
 {type:'middle',n:32,title:'Заполни середину',answer:5},
 {type:'assemble',n:41,title:'Собери результат',answer:'451'},
 {type:'choice',n:52,title:'Кто быстрее?',answer:572,options:[562,572,582,512]},
 {type:'catch',n:34,title:'Поймай ответ',answer:374,options:[364,374,384,344]},
 {type:'input',n:61,title:'Введи самостоятельно',answer:671},
 {type:'sprint',n:21,title:'Скоростная серия',series:[21,43,62],answers:[231,473,682]},
 {type:'final',n:72,title:'Финальный расчёт',answer:792}
];
let state,ctx,gain;
function initAudio(){if(ctx){ctx.resume();return}ctx=new(window.AudioContext||window.webkitAudioContext)();gain=ctx.createGain();gain.gain.value=.2;gain.connect(ctx.destination)}
function sound(k){if(!ctx)return;const map={click:[500],correct:[392,523,659],wrong:[170,145],checkpoint:[300,440],combo:[523,659,784],finish:[392,494,587,784,988]},a=map[k]||[440];a.forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+i*.07;o.type=k==='checkpoint'?'square':'triangle';o.frequency.value=f;g.gain.setValueAtTime(.08,t);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.connect(g).connect(gain);o.start(t);o.stop(t+.2)})}
function fresh(){return{round:0,score:0,combo:0,bestCombo:0,mistakes:0,hints:0,start:Date.now(),sprint:0,assembled:''}}
window.openTournament=()=>{initAudio();sound('click');state=fresh();document.querySelectorAll('.checkpoints i').forEach(x=>x.classList.remove('on'));document.querySelector('#foxMarker').style.setProperty('--run','0%');update();intro();if(!dialog.open)dialog.showModal()};
function intro(){document.querySelector('#boardEquation').textContent='23 × 11';document.querySelector('#boardResult').textContent='2 [?] 3';task.innerHTML=`<div class="tournament-intro"><small>БЛОК 2</small><h2>Секретный приём 11</h2><p>Раздвинь цифры. Найди их сумму. Поставь её в середину.</p><div class="secret-demo"><b>2</b><span>2 + 3 = <em>?</em></span><b>3</b></div><button id="showSecret">ПОКАЖИ</button></div>`;document.querySelector('#showSecret').onclick=()=>{sound('correct');document.querySelector('.secret-demo em').textContent='5';document.querySelector('#boardResult').textContent='253';document.querySelector('#foxSpeech').textContent='Вот и секрет! Крайние цифры оставляем, между ними ставим сумму.';document.querySelector('#showSecret').textContent='В ТУРНИР';document.querySelector('#showSecret').onclick=render}}
function render(){const r=rounds[state.round];msg.textContent='';state.assembled='';document.querySelector('#roundLabel').textContent=`РАУНД ${state.round+1} / 7`;document.querySelector('#boardEquation').textContent=`${r.n} × 11`;document.querySelector('#boardResult').textContent='?';document.querySelector('#foxSpeech').textContent=['Перетащи сумму цифр в середину.','Крайние цифры остаются на местах.','Собери ответ одним взглядом!','Лови верный жетон. Он где-то на дорожке.','Теперь без подсказок на табло.','Три примера подряд — держим темп!','Финальный рывок. Покажи приём целиком!'][state.round];let ui='';if(r.type==='middle')ui=middleUI(r);if(r.type==='assemble')ui=assembleUI(r);if(r.type==='choice')ui=choiceUI(r);if(r.type==='catch')ui=catchUI(r);if(r.type==='input'||r.type==='final')ui=inputUI(r);if(r.type==='sprint')ui=sprintUI(r);task.innerHTML=`<div class="tournament-task-head"><small>${r.title}</small><h2>${r.n} × 11</h2></div><div class="tournament-mechanic">${ui}</div>`;bind(r)}
function middleUI(r){const a=Math.floor(r.n/10),b=r.n%10;return`<div class="digit-build"><b>${a}</b><div id="middleSlot">?</div><b>${b}</b></div><p>${a} + ${b} = ?</p><div class="number-tokens">${[a+b-1,a+b,a+b+1].map(x=>`<button data-middle="${x}">${x}</button>`).join('')}</div>`}
function assembleUI(r){const digits=String(r.answer).split('').sort(()=>Math.random()-.5);return`<div class="answer-slots" id="answerSlots"><i></i><i></i><i></i></div><div class="number-tokens">${digits.map(x=>`<button data-digit="${x}">${x}</button>`).join('')}</div><button class="tournament-confirm" id="assembleCheck">ПРОВЕРИТЬ</button>`}
function choiceUI(r){return`<div class="tournament-answers">${r.options.map(x=>`<button data-answer="${x}">${x}</button>`).join('')}</div>`}
function catchUI(r){return`<div class="moving-tokens">${r.options.map((x,i)=>`<button style="--delay:${i*.55}s" data-answer="${x}">${x}</button>`).join('')}</div>`}
function inputUI(){return`<form id="tournamentForm"><input type="number" inputmode="numeric" placeholder="Ответ" required autofocus><button>ЗАФИКСИРОВАТЬ</button></form>`}
function sprintUI(r){const n=r.series[state.sprint];return`<div class="sprint-count">${state.sprint+1} / 3</div><h3>${n} × 11 = ?</h3><form id="tournamentForm"><input type="number" inputmode="numeric" required autofocus><button>ДАЛЬШЕ</button></form>`}
function bind(r){task.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>check(+b.dataset.answer,b));task.querySelectorAll('[data-middle]').forEach(b=>{let sx,sy;b.onclick=()=>check(+b.dataset.middle,b);b.onpointerdown=e=>{sx=e.clientX;sy=e.clientY;b.setPointerCapture(e.pointerId)};b.onpointermove=e=>{if(sx!==undefined)b.style.transform=`translate(${e.clientX-sx}px,${e.clientY-sy}px) scale(1.08)`};b.onpointerup=e=>{b.style.transform='';sx=undefined;const z=document.querySelector('#middleSlot').getBoundingClientRect();if(e.clientX>z.left&&e.clientX<z.right&&e.clientY>z.top&&e.clientY<z.bottom)b.click()}});task.querySelectorAll('[data-digit]').forEach(b=>b.onclick=()=>{sound('click');if(state.assembled.length<3){state.assembled+=b.dataset.digit;b.disabled=true;const slots=document.querySelectorAll('#answerSlots i');slots[state.assembled.length-1].textContent=b.dataset.digit}});const ac=document.querySelector('#assembleCheck');if(ac)ac.onclick=()=>state.assembled===r.answer?check(r.answer,ac):wrong(ac);const f=document.querySelector('#tournamentForm');if(f)f.onsubmit=e=>{e.preventDefault();const v=+f.querySelector('input').value;if(r.type==='sprint')sprintCheck(r,v,f.querySelector('button'));else check(v,f.querySelector('button'))}}
function sprintCheck(r,v,b){const answer=r.answers[state.sprint];if(v!==answer)return wrong(b);sound('combo');state.score+=120;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);state.sprint++;if(state.sprint===3){state.sprint=0;completeRound()}else{document.querySelector('#boardEquation').textContent=`${r.series[state.sprint]} × 11`;task.querySelector('.tournament-mechanic').innerHTML=sprintUI(r);bind(r)}update()}
function check(v,b){const r=rounds[state.round];if(String(v)!==String(r.answer))return wrong(b);sound(state.combo>=2?'combo':'correct');b.classList.add('correct');const answer=r.answer;document.querySelector('#boardResult').textContent=`${r.n} × 11 = ${answer}`;state.score+=100+state.combo*20;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);setTimeout(completeRound,750);update()}
function wrong(b){sound('wrong');state.mistakes++;state.combo=0;b.classList.add('wrong');msg.textContent='Почти! Проверь сумму двух цифр.';setTimeout(()=>b.classList.remove('wrong'),450);update()}
function completeRound(){sound('checkpoint');document.querySelectorAll('.checkpoints i')[state.round].classList.add('on');state.round++;document.querySelector('#foxMarker').style.setProperty('--run',(state.round/7*100)+'%');update();setTimeout(()=>state.round===7?finish():render(),700)}
function update(){document.querySelector('#tournamentScore').textContent=state.score;document.querySelector('#tournamentCombo').textContent='×'+state.combo;document.querySelector('#tournamentRound').textContent=state.round+' / 7';document.querySelector('#tournamentDots').textContent=Array.from({length:7},(_,i)=>i<state.round?'●':'○').join(' ');document.querySelector('#powerFill').style.width=(state.round/7*100)+'%'}
function stars(){return state.mistakes<=1&&state.hints<=1?3:state.mistakes<=4?2:1}
function finish(){sound('finish');const s=stars(),time=Math.round((Date.now()-state.start)/1000);document.querySelector('#boardResult').textContent='ФИНИШ!';task.innerHTML=`<div class="tournament-result"><span>🏅</span><h2>Секретный приём освоен!</h2><p>7 / 7 · Лучшее комбо ×${state.bestCombo}</p><h3>${state.score} очков</h3><strong>★ ${s} &nbsp; +70 XP &nbsp; ● 30</strong><div><button id="tournamentAgain">ПОВТОРИТЬ ЭТАП</button><button id="tournamentHome">НА ПОЛЯНУ</button></div></div>`;localStorage.setItem('tournament11Progress',JSON.stringify({level2Completed:true,level2BestScore:state.score,level2BestTime:time,level2BestCombo:state.bestCombo,level2Stars:s,secret11Badge:true}));window.dispatchEvent(new CustomEvent('tournament-complete',{detail:{xp:70,score:state.score,coins:30,stars:s}}));document.querySelector('#tournamentAgain').onclick=()=>window.openTournament();document.querySelector('#tournamentHome').onclick=()=>dialog.close()}
document.querySelector('#tournamentExit').onclick=()=>dialog.close();document.querySelector('#tournamentHint').onclick=()=>{state.hints++;const r=rounds[state.round],a=Math.floor(r.n/10),b=r.n%10;msg.textContent=`Оставь ${a} и ${b} по краям, между ними поставь ${a}+${b}.`};document.querySelector('#tournamentSound').onclick=e=>{gain.gain.value=gain.gain.value?0:.2;e.currentTarget.textContent=gain.gain.value?'🔊':'🔇'}
})();
