(()=>{
const dialog=document.querySelector('#trailGame'),task=document.querySelector('#trailTask'),message=document.querySelector('#trailMessage');
const levels=[
 {type:'choice',title:'Доски для моста',story:'Для 3 секций нужно 6 досок. Сколько досок понадобится для 5 секций?',equation:'3 : 5 = 6 : x',options:[8,9,10,12],answer:10,success:'Первая секция готова!'},
 {type:'input',title:'Верёвки',story:'4 метра верёвки весят 120 граммов. Сколько весят 7 метров?',equation:'4 : 7 = 120 : x',answer:210,success:'Верёвки натянуты!'},
 {type:'drag',title:'Крепление опоры',story:'Перетащи равное отношение в крепёжный паз.',equation:'2 : 3',options:['4 : 6','6 : 8','8 : 9','10 : 12'],answer:'4 : 6',success:'Опора установлена!'},
 {type:'balance',title:'Баланс моста',story:'3 балки весят 12 кг. Подбери вес 5 таких балок и уравновесь платформу.',equation:'3 : 5 = 12 : x',options:[16,18,20,24],answer:20,success:'Мост выровнен!'},
 {type:'dial',title:'Кодовый механизм',story:'Поверни диск на верное число и запусти механизм.',equation:'6 : x = 9 : 12',options:[4,6,8,9,12],answer:8,success:'Механизм запущен!'}
];
let state,dragValue,sound=true,audioCtx,master,ambience;
function initAudio(){if(audioCtx){audioCtx.resume();return}audioCtx=new(window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=.22;master.connect(audioCtx.destination);const n=audioCtx.sampleRate*2,b=audioCtx.createBuffer(1,n,audioCtx.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<n;i++){last=(last+.02*(Math.random()*2-1))/.998;d[i]=last*.08}ambience=audioCtx.createBufferSource();const f=audioCtx.createBiquadFilter();f.type='lowpass';f.frequency.value=900;ambience.buffer=b;ambience.loop=true;ambience.connect(f).connect(master);ambience.start()}
function tone(freq=440,duration=.09,type='sine',gain=.13,delay=0){if(!sound||!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(gain,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(master);o.start(t);o.stop(t+duration+.02)}
function sfx(name){if(name==='click')tone(520,.05,'triangle',.08);if(name==='tick')tone(240,.055,'square',.07);if(name==='wrong'){tone(170,.15,'sawtooth',.08);tone(135,.18,'sawtooth',.06,.08)}if(name==='build'){tone(115,.12,'triangle',.1);tone(180,.16,'triangle',.08,.11);tone(290,.2,'sine',.1,.22)}if(name==='mechanism')[180,230,290,370,470].forEach((f,i)=>tone(f,.16,'square',.06,i*.11));if(name==='reward')[392,494,587,784].forEach((f,i)=>tone(f,.3,'triangle',.1,i*.12))}
let natureStarted=false,birdTimer;
function startNature(){if(natureStarted||!audioCtx)return;natureStarted=true;const n=audioCtx.sampleRate*3,b=audioCtx.createBuffer(2,n,audioCtx.sampleRate);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(.35+Math.sin(i*.00017)*.1)}const water=audioCtx.createBufferSource(),band=audioCtx.createBiquadFilter(),g=audioCtx.createGain();water.buffer=b;water.loop=true;band.type='bandpass';band.frequency.value=1450;band.Q.value=.45;g.gain.value=.32;water.connect(band).connect(g).connect(master);water.start();birdTimer=setInterval(()=>{if(!sound||!dialog.open)return;const base=900+Math.random()*500;tone(base,.16,'sine',.055);tone(base*1.35,.12,'sine',.045,.13);tone(base*1.12,.1,'sine',.035,.27)},3200+Math.random()*1800)}
function fresh(){return{current:0,completed:0,correct:0,mistakes:0,hints:0,xp:0,coins:0,start:Date.now(),selectedDial:4}}
function buildBridge(){const g=document.querySelector('#bridgePlanks');g.innerHTML='';for(let i=0;i<5;i++){const group=document.createElementNS('http://www.w3.org/2000/svg','g');group.classList.add('plank-group');group.dataset.stage=i;for(let j=0;j<4;j++){const r=document.createElementNS('http://www.w3.org/2000/svg','rect');r.setAttribute('x',90+i*125+j*29);r.setAttribute('y',115+Math.abs(2-i)*12+j*1.5);r.setAttribute('width','25');r.setAttribute('height','42');r.setAttribute('rx','4');group.append(r)}g.append(group)}}
window.openTrailGame=()=>{initAudio();if(master)master.gain.value=sound ? .55 : 0;startNature();tone(660,.12,'triangle',.18);sfx('click');state=fresh();buildBridge();update();showIntro();if(!dialog.open)dialog.showModal()};
function showIntro(){task.innerHTML=`<div class="trail-intro"><small>ЛЕСНАЯ МИССИЯ</small><h2>Разрушенный мост</h2><p>Восстанови пять частей моста и открой путь к лагерю команды.</p><div><span>5 заданий</span><span>≈ 5 минут</span><span>★ до 3 звёзд</span></div><button id="beginTrail">НАЧАТЬ ПРИКЛЮЧЕНИЕ</button></div>`;document.querySelector('#beginTrail').onclick=()=>{sfx('click');renderLevel()}}
function renderLevel(){const l=levels[state.current];state.locked=false;message.textContent='';document.querySelector('#raccoonSpeech').textContent=raccoonLine();let control='';if(l.type==='choice')control=buttons(l.options);if(l.type==='input')control=`<form id="numberForm"><label>x = <input id="numberAnswer" type="number" inputmode="numeric" required autofocus></label><button>Проверить</button></form>`;if(l.type==='drag')control=`<div class="drop-zone" id="dropZone">Перетащи сюда</div><div class="drag-options">${l.options.map(x=>`<button class="drag-chip" data-value="${x}" aria-label="Перетащить отношение ${x} в паз">${x}</button>`).join('')}</div>`;if(l.type==='balance')control=`<div class="scale"><div class="scale-beam"><span>3 балки<br><b>12 кг</b></span><i></i><span>5 балок<br><b id="balanceWeight">?</b></span></div></div>${buttons(l.options,'кг')}`;if(l.type==='dial')control=`<div class="lock-machine"><div class="lock-lights"><i></i><i></i><i></i></div><div class="dial-arrow">▼</div><div class="dial-wheel" id="dialWheel">${l.options.map((x,i)=>`<button style="--i:${i}" data-value="${x}">${x}</button>`).join('')}</div><strong id="dialValue">4</strong></div><button class="confirm-dial" id="confirmDial">ЗАПУСТИТЬ МЕХАНИЗМ</button>`;task.innerHTML=`<div class="task-head"><small>ЭТАП ${state.current+1} / 5</small><h2>${l.title}</h2><p>${l.story}</p></div><div class="equation">${l.equation}</div><div class="mechanic">${control}</div>`;bind(l)}
function buttons(arr,suffix=''){return`<div class="trail-answers">${arr.map(x=>`<button data-answer="${x}">${x}${suffix?' '+suffix:''}</button>`).join('')}</div>`}
function bind(l){task.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{sfx('click');check(typeValue(b.dataset.answer,l.answer),b)});const form=document.querySelector('#numberForm');if(form)form.onsubmit=e=>{e.preventDefault();sfx('click');check(+document.querySelector('#numberAnswer').value,form.querySelector('button'))};if(l.type==='drag')bindDrag(l);if(l.type==='balance')task.querySelectorAll('[data-answer]').forEach(b=>b.onmouseenter=()=>document.querySelector('#balanceWeight').textContent=b.dataset.answer+' кг');if(l.type==='dial'){task.querySelectorAll('#dialWheel button').forEach(b=>b.onclick=()=>{sfx('tick');state.selectedDial=+b.dataset.value;document.querySelector('#dialValue').textContent=state.selectedDial;document.querySelector('#dialWheel').style.transform=`rotate(${-l.options.indexOf(state.selectedDial)*72}deg)`;task.querySelectorAll('#dialWheel button').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelector('#confirmDial').onclick=()=>{sfx('mechanism');document.querySelector('.lock-machine').classList.add('activating');setTimeout(()=>check(state.selectedDial,document.querySelector('#confirmDial')),500)}}
}
function typeValue(v,a){return typeof a==='number'?+v:v}
function bindDrag(l){document.querySelectorAll('.drag-chip').forEach(chip=>{let sx=0,sy=0;chip.onpointerdown=e=>{dragValue=chip.dataset.value;sx=e.clientX;sy=e.clientY;chip.setPointerCapture(e.pointerId);chip.classList.add('dragging')};chip.onpointermove=e=>{if(!chip.classList.contains('dragging'))return;chip.style.transform=`translate(${e.clientX-sx}px,${e.clientY-sy}px) scale(1.05)`};chip.onpointerup=e=>{chip.classList.remove('dragging');chip.style.transform='';const r=document.querySelector('#dropZone').getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)check(dragValue,document.querySelector('#dropZone'))};chip.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();check(chip.dataset.value,document.querySelector('#dropZone'))}}})}
function check(value,el){if(state.locked)return;const l=levels[state.current];if(value===l.answer){state.locked=true;sfx('build');state.correct++;state.xp+=l.type==='dial'?20:10;state.completed++;el.classList.add('correct');message.textContent=`+${l.type==='dial'?20:10} XP`;document.querySelector('#raccoonSpeech').textContent=l.success;document.querySelector('#raccoonGuide').classList.add('celebrate');update();setTimeout(()=>{document.querySelector('#raccoonGuide').classList.remove('celebrate');state.current++;state.current===levels.length?finish():renderLevel()},1200)}else{sfx('wrong');state.mistakes++;el.classList.add('wrong');message.textContent=['Почти. Проверь отношение.','Здесь спрятался другой множитель.','Попробуй ещё — мост подождёт.'][state.mistakes%3];setTimeout(()=>el.classList.remove('wrong'),500)}}
function update(){document.querySelector('#trailProgress').textContent=state.completed+' / 5';document.querySelector('#trailDots').textContent=Array.from({length:5},(_,i)=>i<state.completed?'●':'○').join(' ');document.querySelector('#trailCoins').textContent=state.coins;document.querySelectorAll('.plank-group').forEach((p,i)=>p.classList.toggle('built',i<state.completed));document.querySelector('.bridge').classList.toggle('complete',state.completed===5)}
function raccoonLine(){return['Начнём с досок. Тут всё держится на пропорциях.','Верёвка любит точный расчёт.','Найди пару — опора встанет на место.','Баланс важнее силы.','Последний замок. Не промахнись с кодом!'][state.current]}
function hint(){state.hints++;const hints=['6 досок — это по 2 на секцию.','Сначала найди вес одного метра.','Ищи отношение, где оба числа увеличены одинаково.','Одна балка весит 4 кг.','9 : 12 сократи до 3 : 4.'][state.current];message.textContent=hints}
function stars(){if(state.mistakes<=1&&state.hints<=1)return 3;if(state.mistakes<=4)return 2;return 1}
function finish(){state.coins=30;const s=stars(),time=Math.round((Date.now()-state.start)/1000);document.querySelector('#trailStars').textContent='★'.repeat(s)+'☆'.repeat(3-s);document.querySelector('#trailCoins').textContent=30;task.innerHTML=`<div class="trail-result"><span>🏆</span><h2>Мост восстановлен!</h2><p>Енот добрался до лагеря, а тропа снова открыта.</p><div><b>5 / 5</b><span>Ошибки: ${state.mistakes}</span><span>Подсказки: ${state.hints}</span><span>Время: ${Math.floor(time/60)}:${String(time%60).padStart(2,'0')}</span></div><h3>★ ${s} &nbsp; +${state.xp+50} XP &nbsp; ● 30</h3><button id="trailAgain">СЫГРАТЬ ЕЩЁ</button><button id="trailHome">ВЕРНУТЬСЯ НА ПОЛЯНУ</button></div>`;const saved={bestStars:Math.max(s,+localStorage.getItem('trail-best-stars')||0),bestTime:time,totalXP:state.xp+50,coins:30,completed:true};localStorage.setItem('proportionsTrailProgress',JSON.stringify(saved));window.dispatchEvent(new CustomEvent('trail-complete',{detail:{xp:state.xp+50,coins:30,stars:s}}));document.querySelector('#trailAgain').onclick=()=>window.openTrailGame();document.querySelector('#trailHome').onclick=()=>dialog.close()}
document.querySelector('#trailHint').onclick=hint;document.querySelector('#trailExit').onclick=()=>dialog.close();document.querySelector('#trailSound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'🔊':'🔇'};const pause=document.querySelector('#pauseScreen');document.querySelector('#trailPause').onclick=()=>pause.hidden=false;pause.onclick=e=>{const a=e.target.dataset.pause;if(a==='resume')pause.hidden=true;if(a==='sound'){sound=!sound;e.target.textContent='Звук: '+(sound?'вкл':'выкл')}if(a==='restart'){pause.hidden=true;window.openTrailGame()}if(a==='exit')dialog.close()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&dialog.open){e.preventDefault();dialog.close()}})
const finishWithoutSound=finish;finish=()=>{sfx('reward');finishWithoutSound()};
document.querySelector('#trailHint').onclick=()=>{sfx('click');hint()};
document.querySelector('#trailSound').onclick=e=>{sound=!sound;if(master)master.gain.setTargetAtTime(sound ? .55 : 0,audioCtx.currentTime,.04);e.currentTarget.textContent=sound?'🔊':'🔇'};
})();
